---

pilot:
  ros__parameters:
    type: system
    parts:
      controller_server
      bt_navigator
      bt_bica
    modes:
      __DEFAULT__:
        controller_server: active
        bt_navigator: active
        bt_bica: active
      MODERATE:
        controller_server: active.SLOW
        bt_navigator: active.ROUNDROBIN
      PERFORMANCE:
        controller_server: active.FAST
        bt_navigator: active.SIMPLE
      RECOVERY:
        controller_server: active.RECOVERY
        bt_navigatior: active.RECOVERY
        bt_bica: active.RECOVERY

bt_navigator:
  ros__parameters:
    type: node
    modes:
      __DEFAULT__:
        ros__parameters:
          bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
      ROUNDROBIN:
        ros__parameters:
          bt_xml_filename: "navigate_w_replanning_and_round_robin_recovery.xml"
      SIMPLE:
        ros__parameters:
          bt_xml_filename: "navigate_w_replanning.xml"
      RECOVERY:
          bt_xml_filename: "navigate_w_replanning.xml" #CAMBIAR

controller_server:
  ros__parameters:
    type: node
    modes:
      __DEFAULT__:
        ros__parameters:
          max_vel_x: 0.26
          max_vel_y: 0.0
          max_vel_theta: 1.0
      SLOW:
        ros__parameters:
          max_vel_x: 0.2
          max_vel_y: 0.0
          max_vel_theta: 0.6
      FAST:
        ros__parameters:
          max_vel_x: 0.35
          max_vel_y: 0.0
          max_vel_theta: 1.3
      RECOVERY: #CAMBIAR
        ros__parameters:
          max_vel_x: 0.00
          max_vel_y: 0.0
          max_vel_theta: 0.0

bt_bica:
  ros__parameters:
    type: node
    modes:
      __DEFAULT__:
        ros__parameters:
          bt_xml_filename: "bt.xml"
      RECOVERY:
          bt_xml_filename: "no_existe_todavía.xml" 