---

pilot:
  ros__parameters:
    type: system
    parts:
      controller_server
      bt_navigator
    modes:
      __DEFAULT__:
        controller_server: active
        bt_navigator: active
      MODERATE:
        controller_server: active.SLOW
        bt_navigator: active.ROUNDROBIN
      PERFORMANCE:
        controller_server: active.FAST
        bt_navigator: active.SIMPLE
      LOW_BATTERY:
        controller_server: active.LOW_BATTERY
        bt_navigator: active.LOW_BATTERY
      LOST:
        controller_server: active.LOST
        bt_navigator: active.LOST
      OBSTRUCTED:
        controller_server: active.OBSTRUCTED
        bt_navigator: active.OBSTRUCTED
      NORMAL:
        controller_server: active.NORMAL
        bt_navigator: active.NORMAL

bt_navigator:
  ros__parameters:
    type: node
    modes:
      __DEFAULT__:
        ros__parameters:
          bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
      ROUNDROBIN:
        ros__parameters:
          bt_xml_filename: "navigate_w_replanning_and_round_robin_recovery.xml"
      SIMPLE:
        ros__parameters:
          bt_xml_filename: "navigate_w_replanning.xml"
      LOW_BATTERY:
        ros__parameters:
          bt_xml_filename: "navigate_w_replanning_and_battery_warning.xml"
      LOST:
        ros__parameters:
          bt_xml_filename: "navigate_w_replanning_and_robot_lost.xml"
      OBSTRUCTED:
        ros__parameters:
          bt_xml_filename: "navigate_w_replanning_and_obstacle_detected.xml"
      NORMAL:
        ros__parameters:
          bt_xml_filename: "navigate_w_replanning_and_recovery.xml"

controller_server:
  ros__parameters:
    type: node
    modes:
      __DEFAULT__:
        ros__parameters:
          max_vel_x: 0.26
          max_vel_y: 0.0
          max_vel_theta: 1.0
      SLOW:
        ros__parameters:
          max_vel_x: 0.2
          max_vel_y: 0.0
          max_vel_theta: 0.6
      FAST:
        ros__parameters:
          max_vel_x: 0.35
          max_vel_y: 0.0
          max_vel_theta: 1.3
      LOW_BATTERY: 
        ros__parameters:
          max_vel_x: 0.2
          max_vel_y: 0.0
          max_vel_theta: 0.6
      LOST: 
        ros__parameters:
          max_vel_x: 0.0
          max_vel_y: 0.0
          max_vel_theta: 0.0
      OBSTRUCTED: 
        ros__parameters:
          max_vel_x: 0.0
          max_vel_y: 0.0
          max_vel_theta: 0.0
      NORMAL:
        ros__parameters:
          max_vel_x: 0.26
          max_vel_y: 0.0
          max_vel_theta: 1.0