rplidar_node:
  ros__parameters:
    serial_port: /dev/rplidar
    serial_baudrate: 115200
    frame_id: laser_frame
    inverted: false
    angle_compensate: true
    scan_mode: Boost

joint_state_publisher:
  ros__parameters:
    publish_default_positions: true
    rate: 30
