---

pilot:
  ros__parameters:
    type: system
    parts:
      amcl
      bt_navigator
      controller_server
      pointcloud_to_laser
    modes:
      __DEFAULT__:
        amcl: active
        bt_navigator: active
        controller_server: active
        pointcloud_to_laser: inactive
      DEGRADED:
        amcl: active.DEGRADED
        bt_navigator: active
        controller_server: active.DEGRADED
        pointcloud_to_laser: active
      PERFORMANCE:
        amcl: active
        bt_navigator: active.SIMPLE
        controller_server: active.FAST
        pointcloud_to_laser: inactive
      ENERGY_SAVING:
        amcl: active
        bt_navigator: active.LOW_BATTERY
        controller_server: active.SLOW
        pointcloud_to_laser: inactive
      SLOW:
        amcl: active
        bt_navigator: active
        controller_server: active.SLOW
        pointcloud_to_laser: inactive

amcl:
  ros__parameters:
    type: node
    modes:
      __DEFAULT__:
        ros__parameters:
          transform_tolerance: 0.2
      DEGRADED: 
        ros__parameters:
          transform_tolerance: 2.5 

bt_navigator:
  ros__parameters:
    type: node
    modes:
      __DEFAULT__:
        ros__parameters:
          bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
      SIMPLE:
        ros__parameters:
          bt_xml_filename: "navigate_w_replanning.xml"
      LOW_BATTERY:
        ros__parameters:
          bt_xml_filename: "navigate_w_replanning_and_battery_warning.xml"

pointcloud_to_laser:
  ros__parameters:
    type: node
    modes:
      __DEFAULT__:
        ros__parameters:
          pointcloud_to_laser_test: "0"

controller_server:
  ros__parameters:
    type: node
    modes:
      __DEFAULT__:
        ros__parameters:
          FollowPath.max_vel_x: 0.26
          FollowPath.max_vel_theta: 1.0
          FollowPath.transform_tolerance: 0.2
      SLOW:
        ros__parameters:
          FollowPath.max_vel_x: 0.2
          FollowPath.max_vel_theta: 0.6
      FAST:
        ros__parameters:
          FollowPath.max_vel_x: 0.35
          FollowPath.max_vel_theta: 1.3
      DEGRADED: 
        ros__parameters:
          FollowPath.max_vel_x: 0.1
          FollowPath.max_vel_theta: 0.4
          FollowPath.transform_tolerance: 2.5