---

pilot:
  ros__parameters:
    type: system
    parts:
      amcl
      bt_navigator
      controller_server
      pointcloud_to_laser
      laser_resender
    modes:
      __DEFAULT__:
        amcl: inactive
        bt_navigator: inactive
        controller_server: inactive
        pointcloud_to_laser: inactive
        laser_resender: inactive
      f3_v3_r1:
        amcl: active
        bt_navigator: active
        controller_server: active
        pointcloud_to_laser: inactive
        laser_resender: active
      # [SkillRealization RGBD camera]
      DEGRADED:
        amcl: active.DEGRADED
        bt_navigator: active
        controller_server: active.DEGRADED
        pointcloud_to_laser: active
        laser_resender: unconfigured
      f1_v1_r2:
        amcl: active
        bt_navigator: active.SIMPLE
        controller_server: active.FAST
        pointcloud_to_laser: inactive
        laser_resender: active
      f1_v1_r3:
        amcl: active
        bt_navigator: active.LOW_BATTERY
        controller_server: active.SLOW
        pointcloud_to_laser: inactive
        laser_resender: active
      f1_v1_r1:
        amcl: active
        bt_navigator: active
        controller_server: active.SLOW
        pointcloud_to_laser: inactive
        laser_resender: active
    # [Rule to switch]
    rules:
      degrade_from_NORMAL:
        if_target: active.NORMAL
        if_part: [laser_resender, unconfigured]
        new_target: active.DEGRADED

amcl:
  ros__parameters:
    type: node
    modes:
      __DEFAULT__:
        ros__parameters:
          transform_tolerance: 0.2
          alpha1: 0.2
          alpha2: 0.2
          alpha3: 0.2
          alpha4: 0.2
          alpha5: 0.2
      DEGRADED: 
        ros__parameters:
          transform_tolerance: 2.5
          alpha1: 0.05
          alpha2: 0.05
          alpha3: 0.05
          alpha4: 0.05
          alpha5: 0.05

bt_navigator:
  ros__parameters:
    type: node
    modes:
      __DEFAULT__:
        ros__parameters:
          default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
      SIMPLE:
        ros__parameters:
          default_bt_xml_filename: "navigate_w_replanning.xml"
      LOW_BATTERY:
        ros__parameters:
          default_bt_xml_filename: "navigate_w_replanning_and_battery_warning.xml"

laser_resender:
  ros__parameters:
    type: node
    modes:
      __DEFAULT__:
        ros__parameters:
          node_name: "laser_resender"

pointcloud_to_laser:
  ros__parameters:
    type: node
    modes:
      __DEFAULT__:
        ros__parameters:
          node_name: "pointcloud_to_laser"

controller_server:
  ros__parameters:
    type: node
    modes:
      __DEFAULT__:
        ros__parameters:
          FollowPath.max_vel_x: 0.4
          FollowPath.max_speed_xy: 0.4
          FollowPath.max_vel_theta: 1.25
          FollowPath.transform_tolerance: 0.2
      SLOW:
        ros__parameters:
          FollowPath.max_vel_x: 0.1
          FollowPath.max_speed_xy: 0.1
          FollowPath.max_vel_theta: 0.5
          FollowPath.transform_tolerance: 0.2
      FAST:
        ros__parameters:
          FollowPath.max_vel_x: 0.5
          FollowPath.max_speed_xy: 0.5
          FollowPath.max_vel_theta: 1.5
          FollowPath.transform_tolerance: 0.2
      DEGRADED:
        ros__parameters:
          FollowPath.max_vel_x: 0.1
          FollowPath.max_speed_xy: 0.1
          FollowPath.max_vel_theta: 0.5
          FollowPath.transform_tolerance: 2.5
